### ISSUE TITLE
Need to use `plot_id` when creating `population_id`

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#1]
Referencing this [comment](https://github.com/traitecoevo/austraits.build/pull/749#issuecomment-1610297632) from [austraits.build](https://github.com/traitecoevo/austraits.build), brought to our attention by @ehwenk:

In order to pivot AusTraits wider, `plot_id` is needed in the list of pivot variables. Previously `plot_id` was not included, as it is used to create `population_id`'s . However, Yang_2023 is an example of a study without "locations" (species-wide values), but there are some plot contexts. In this study, `population_id`'s remain NA. It seems that we might need to tweak `process.R` to have `population_id`'s created from `plot_id` (or `treatment_id`) even if there aren't any locations specified.

Also need `life_stage` in list of variables to `pivot_wider`.

This is related to this [issue](https://github.com/traitecoevo/austraits.build/issues/746).

**Comment by ehwenk** [comment]
This was actually (mostly) a problem with the metadata in Yang_2023 and is fixed on a branch in `austraits.build`. The problem was that `population_id`'s are only created if `entity_type` is population or individual and all entity types in this dataset were species - except for a few traits.

However, fixing the problem, exposed the still-to-fix issue #34.
