### ISSUE TITLE
Update traits.yml

### ISSUE THREAD

**Issue by hrlai** [traitecoevo/traits.build#182]
Hi there, some of the new traits included in `austraits` don't seem to be in `traits.build` yet, is that true? For example I tried to add `leaf_dry_matter_content` but it wasn't found in `tests/testthat/config/traits.yml`...

**Comment by ehwenk** [comment]
@hrlai The `traits.yml` file within tests is just a subset of the full AusTraits `traits.yml` file (https://github.com/traitecoevo/austraits.build/blob/develop/config/traits.yml) to run the tests on the traits.build package. If you want the full dictionary, grab it from the austraits.build repository or I can point you to the code to generate it from the APD (the two *.csv files in https://github.com/traitecoevo/APD/tree/master/release/2.0.0 merge to create it).

But if you were actually getting an error because we missed a necessary trait for the tests, let me know.

**Comment by hrlai** [comment]
Ah I see! Thanks. For now I think it'll suffice to just copy it from `austraits.build`. Later I might be tempted to copy the entire `scripts` folder to my own traits.build repo, and build the yml occassionally from there :)

Happy to consider this closed.

**Comment by ehwenk** [comment]
Perfect! And if you develop additional trait definitions for your own work, let us know.

**Comment by ehwenk** [comment]
@hrlai I also want to overall apologies for the branches that haven't been merged in, including not yet getting develop merged back into master. It was meant to happen before ESA, but we just ran out of time. And it has actually been great to have someone testing our package for us and picking up other bugs we missed.

**Comment by hrlai** [comment]
All good! This is already amazing work and really glad that you guys are generously sharing the codebase. You don't know how much time this has saved me compared to doing it from scratch!
