### ISSUE TITLE
Add `dataset_test` test for checking context metadata values are in the data

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#63]
Currently there is a [test](https://github.com/traitecoevo/traits.build/blob/b6239ecfeec37695aa7cb862e04f32daedd842f1/R/testdata.R#L554) in `dataset_test` that checks if context values in the data are not found in context metadata. I don't believe there is a test for the other way around, i.e. check that context metadata values are actually in the data. This means that there's rows in the `contexts` table that have no `link_id` and `link_vals`. 

An alternative is that we allow these context values in the metadata but remove it from the `contexts` table during `process.R`. I think it's safer to let the user remove non-existent context values from the metadata though.

**Comment by ehwenk** [comment]
@yangsophieee I think the test does work both ways, because when I made the changes to context processing (https://github.com/traitecoevo/traits.build/pull/59) the tests detected ~5 studies where metadata[["contexts"]] detected context property values that weren't in the respective datasets and threw errors.

And on that branch, there were no blank `link_id` or `link_vals` at the end. 

But I didn't tweak any of the tests for this to happen.
