### ISSUE TITLE
Update schema for reading in metadata from different sections

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#67]
Right now `dataset_test` doesn't allow `basis_of_value`, `value_type` to be read in from the dataset level and `collection_date` from the trait level (e.g. in Test Dataset 1). I'm sure there's other metadata fields to review, which we may or may not want to be read from these different levels.

**Comment by ehwenk** [comment]
I think `basis_of_value` and `value_type` really should remain linked to a single trait, because they should really be referring to the values for a specific trait - like units. For a wide dataset, that means they should always be specified at the trait level (fixed value or column). There are of course datasets where you could shortcut this and fill it out once at the dataset level, but I don't think that would be a great protocol to encourage. For long datasets, if the information were documented in a column, it does need to be read in at the dataset level - I don't know how we'd deal with that in tests.

**Comment by yangsophieee** [comment]
How about `collection_date` from the trait level? I don't imagine this would be very common.

**Comment by ehwenk** [comment]
I can imagine it happening actually - initially it seemed unlikely but there have actually been studies occasionally with two date columns for different traits. I just sort of assumed we'd have to ignore that but maybe not.
